Parameters:
  StackFilesPathTemplates:
    Description: Name of the bucket
    Type: String
  
  StackFilesRegion:
    Description: Region from stack files in S3
    Type: String
  
  BucketS3Name:
    Description: Name of the bucket
    Type: String

Resources:

  BucketS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketS3Name

Outputs:
  Name:
    Description: Name of S3 bucket
    Value: !Ref 'BucketS3'
    Export:
      Name:
        !Sub '${AWS::StackName}-BucketName'

  Arn:
    Description: Arn of S3 bucket
    Value: !GetAtt 'BucketS3.Arn'
    Export:
      Name:
        !Sub '${AWS::StackName}-BucketArn'

  RegionalDomainName:
    Description: Bucket website endpoint
    Value: !GetAtt 'BucketS3.RegionalDomainName'
    Export:
      Name:
        !Sub '${AWS::StackName}-BucketRegionalDomainName'