Parameters:
  DescriptionCDNOAC:
    Description: A description of the origin access control
    Type: String
    Default: true

  TypeCDNOAC:
    Description: The type of origin that this origin access control is for
    Type: String
    Default: s3

  SigningBehaviorCDNOAC:
    Description: Specifies which requests CloudFront signs
    Type: String
    Default: always

  NameCachePolicy:
    Description: A unique name to identify the cache policy.
    Type: String
    Default: CachingOptimized

  IdOrigin:
    Description: A unique identifier for the origin. This value must be unique within the distribution. 
    Type: String
    Default: ''

  EnabledCdn:
    Description: From this field, you can enable or disable the selected distribution.
    Type: String
    Default: perror

  DefaultRootObjectCdn:
    Description: The object that you want CloudFront to request from your origin
    Type: String
    Default: 'index.html'

  HttpVersionCdn:
    Description: Specify the maximum HTTP version(s) that you want viewers to use to communicate with CloudFront
    Type: String
    Default: http2

  AllowedMethodsCache:
    Description: A complex type that controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin.
    Type: List<String>
    Default: '["GET", "HEAD"]'

  ViewerProtocolPolicyCache:
    Description: El protocolo que los espectadores pueden usar para acceder a los archivos en el origen especificado TargetOriginId.
    Type: String
    Default: 'allow-all'

  BucketS3Name:
    Description: Name of the bucket
    Type: String

Conditions:
  NotExistIdOrigin: !Equals ["", !Ref IdOrigin]

Resources:
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: !Ref DescriptionCDNOAC
        Name: !GetAtt BucketS3.DomainName
        OriginAccessControlOriginType: !Ref TypeCDNOAC
        SigningBehavior: !Ref SigningBehaviorCDNOAC
        SigningProtocol: sigv4

#  CloudFr658327ea-f89d-4fab-a63d-7e88639e58f6hePolicy:
#    Type: AWS::CloudFront::CachePolicy
#    DeletionPolicy: Retain
#    Properties:
#      CachePolicyConfig:
#        Name: !Ref NameCachePolicy
#        MinTTL: 1
#        MaxTTL: 31536000
#        DefaultTTL: 86400
#        ParametersInCacheKeyAndForwardedToOrigin:
#          CookiesConfig: 
#            CookieBehavior: none
#          HeadersConfig:
#            HeaderBehavior: none
#          QueryStringsConfig: 
#            QueryStringBehavior: none
#          EnableAcceptEncodingBrotli: true
#          EnableAcceptEncodingGzip: true

  BucketS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketS3Name
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html