Parameters:
  StackFilesRegion:
    Description: Region from stack files
    Type: String

  StackFilesPathTemplates:
    Description: Path from Files templates stacks
    Type: String
 
  CloudFrontCachePolicyId:
    Description: ID to identify the cache policy.
    Type: String

  DomainName:
    Description: Name of the domain
    Type: String

  HostedZoneId:
    Description: ID to identify the hosted zone from domain.
    Type: String

  BucketWebName:
    Description: Name of S3 bucket
    Type: String

  BucketWebArn:
    Description: Arn of S3 bucket
    Type: String

  BucketWebRegionalDomainName:
    Description: Bucket website endpoint
    Type: String
  
Resources:
  CloudFrontOriginAcl:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://s3"
          - !Sub ".${StackFilesRegion}"
          - !Sub ".amazonaws.com/${StackFilesPathTemplates}/cloudfrontOriginACL.yaml"
      Parameters:
        NameCDNOriginACL: !Ref BucketWebRegionalDomainName
  
  CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://s3"
          - !Sub ".${StackFilesRegion}"
          - !Sub ".amazonaws.com/${StackFilesPathTemplates}/cloudfront.yaml"
      Parameters:
        DomainName: !Ref BucketWebRegionalDomainName
        CDNOriginAccessControlId: !GetAtt CloudFrontOriginAcl.Outputs.id
        CachePolicyId: !Ref CloudFrontCachePolicyId
        AlternativeDomainNames: !Ref DomainName
        CertificateArn: !GetAtt Certificate.Outputs.ARN

  PolicyCloudfrontToS3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://s3"
          - !Sub ".${StackFilesRegion}"
          - !Sub ".amazonaws.com/${StackFilesPathTemplates}/PolicyForCloudFrontPrivateContent.yaml"
      Parameters:
        BucketS3Name: !Ref BucketWebName
        BucketS3ARN: !Ref BucketWebArn
        CloudfrontId: !GetAtt CloudFront.Outputs.Id

  Certificate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://s3"
          - !Sub ".${StackFilesRegion}"
          - !Sub ".amazonaws.com/${StackFilesPathTemplates}/certificate.yaml"
      Parameters:
        DomainName: !Ref DomainName
        AlternativeDomainNames: !Sub "*.${DomainName}"
        HostedZoneId: !Ref HostedZoneId

  Recordset:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://s3"
          - !Sub ".${StackFilesRegion}"
          - !Sub ".amazonaws.com/${StackFilesPathTemplates}/recordset.yaml"
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        DNSName: !GetAtt CloudFront.Outputs.DomainName