Description: >
  Template for build bucket S3

Parameters:
  BucketS3Name:
    Description: Name of the bucket
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketS3Name

Outputs:
  Name:
    Value: !Ref 'S3Bucket'
    Description: Name of S3 bucket

  RegionalDomainName:
    Value: !GetAtt 'S3Bucket.RegionalDomainName'
    Description: Bucket website endpoint
